# encoding: utf-8
# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw]

# Middleman Gems
gem 'middleman-sprockets', '>= 4.1.0'
gem 'middleman-compass', '>= 4.0.0'
gem 'middleman', '>= 4.1.11'
gem 'middleman-livereload', '>= 3.4.7'
gem 'middleman-autoprefixer', '>= 2.7.1'
gem 'middleman-syntax', '>= 3.2.0'
gem 'redcarpet'
